"""Aggregate the verified (crosschecked) 2023 presidential results per state.

Reads data/2023_data/<STATE>_crosschecked.csv (one row per polling unit, with
APC/LP/PDP/NNPP vote counts) and writes backend/app/data_2023.py — a compact
per-state summary used to seed the "Past Election" expert opinion.

Run locally:  python backend/scripts/extract_2023.py
"""
import csv
import pathlib

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
DATA_DIR = REPO_ROOT / "data" / "2023_data"
OUT_FILE = REPO_ROOT / "backend" / "app" / "data_2023.py"

PARTIES = ["APC", "LP", "PDP", "NNPP"]

# App-facing state names; CSV keys are the uppercased form of these.
APP_STATES = [
    "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno",
    "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", "FCT", "Gombe", "Imo",
    "Jigawa", "Kaduna", "Kano", "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa",
    "Niger", "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba",
    "Yobe", "Zamfara",
]
BY_KEY = {s.upper(): s for s in APP_STATES}


def _int(v: str) -> int:
    try:
        n = int(str(v).strip())
        return n if n > 0 else 0
    except (TypeError, ValueError):
        return 0


def main() -> None:
    results: dict[str, dict] = {}
    for path in sorted(DATA_DIR.glob("*_crosschecked.csv")):
        key = path.name.replace("_crosschecked.csv", "").upper()
        state = BY_KEY.get(key)
        if state is None:
            print(f"  ! skipping unmapped state file: {path.name}")
            continue
        totals = {p: 0 for p in PARTIES}
        units = 0
        with path.open(encoding="utf-8", newline="") as fh:
            for row in csv.DictReader(fh):
                units += 1
                for p in PARTIES:
                    totals[p] += _int(row.get(p, 0))
        total_votes = sum(totals.values())
        if total_votes == 0:
            print(f"  ! {state}: zero votes, skipping")
            continue
        scores = {p: round(totals[p] / total_votes * 100, 1) for p in PARTIES}
        leader = max(PARTIES, key=lambda p: totals[p])
        results[state] = {
            "leader": leader,
            "scores": scores,
            "votes": {p: totals[p] for p in PARTIES},
            "total_votes": total_votes,
            "polling_units": units,
        }
        print(f"  {state:12s} -> {leader:5s} {scores}  ({total_votes:,} votes, {units} PUs)")

    lines = [
        '"""Verified 2023 presidential results per state (crosschecked polling units).',
        "",
        "Auto-generated by backend/scripts/extract_2023.py from data/2023_data/*_crosschecked.csv.",
        "Do not edit by hand.",
        '"""',
        "",
        "PAST_ELECTION_2023 = {",
    ]
    for state in APP_STATES:
        d = results.get(state)
        if d is None:
            continue
        lines.append(
            f'    {state!r}: {{"leader": {d["leader"]!r}, "scores": {d["scores"]!r}, '
            f'"total_votes": {d["total_votes"]}, "polling_units": {d["polling_units"]}}},'
        )
    lines.append("}")
    OUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote {len(results)} states -> {OUT_FILE}")


if __name__ == "__main__":
    main()
