"""Extract state facts, stats and 2019 governor races from the election spreadsheet.

Reads data/Nigerian Election Spreadsheet.xlsx and writes backend/app/state_data.py:
  STATE_DATA[state] = { code, capital, census/area, phone lines, voter stats, NIN, 2023,
                        governor_2019: [ {name, party, votes, position} ] }

Run:  python backend/scripts/extract_states.py
"""
import pathlib
import re

import openpyxl

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
XLSX = ROOT / "data" / "Nigerian Election Spreadsheet.xlsx"
OUT = ROOT / "backend" / "app" / "state_data.py"

APP_STATES = [
    "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno",
    "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", "FCT", "Gombe", "Imo",
    "Jigawa", "Kaduna", "Kano", "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa",
    "Niger", "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba",
    "Yobe", "Zamfara",
]
BY_NORM = {re.sub(r"[^a-z]", "", s.lower()): s for s in APP_STATES}


def canon(raw: str) -> str | None:
    if not raw:
        return None
    s = str(raw).strip()
    if s.upper().startswith("FCT"):
        return "FCT"
    s = re.sub(r"\s*State\b.*", "", s)  # drop " State (Capital)"
    s = s.replace("-", " ")
    return BY_NORM.get(re.sub(r"[^a-z]", "", s.lower()))


def num(v):
    if v is None or v == "":
        return None
    try:
        return int(round(float(v)))
    except (TypeError, ValueError):
        return None


def s(v):
    return str(v).strip() if v not in (None, "") else ""


def main():
    wb = openpyxl.load_workbook(XLSX, data_only=True)
    data = {st: {"governor_2019": []} for st in APP_STATES}

    # --- OG Data: phones, voters, 2019 presidential + governor race ---
    og = wb["OG Data"]
    for r in range(3, og.max_row + 1):
        st = canon(og.cell(r, 1).value)
        if not st:
            continue
        cap = ""
        m = re.search(r"\((.+?)\)", s(og.cell(r, 1).value))
        if m:
            cap = m.group(1).strip()
        d = data[st]
        d["capital"] = cap or d.get("capital", "")
        d["active_phone_2021"] = num(og.cell(r, 3).value)
        d["active_phone_2020"] = num(og.cell(r, 4).value)
        d["newly_registered_voters_2022"] = num(og.cell(r, 7).value)
        d["voters_presidential_2019"] = num(og.cell(r, 10).value)
        d["buhari_votes_2019"] = num(og.cell(r, 12).value)
        d["atiku_votes_2019"] = num(og.cell(r, 13).value)
        # governor race: winner(P16,Q17,R18) 2nd(S19,T20,U21) 3rd(V22,W23,X24)
        for name_c, party_c, votes_c, pos in ((16, 17, 18, 1), (19, 20, 21, 2), (22, 23, 24, 3)):
            nm = s(og.cell(r, name_c).value)
            if nm:
                d["governor_2019"].append({"name": nm, "party": s(og.cell(r, party_c).value), "votes": num(og.cell(r, votes_c).value) or 0, "position": pos})

    # --- Sheet9: code, capital, area, census ---
    sh9 = wb["Sheet9"]
    for r in range(1, sh9.max_row + 1):
        st = canon(sh9.cell(r, 1).value)
        if not st:
            continue
        d = data[st]
        d["code"] = s(sh9.cell(r, 2).value)
        d["capital"] = d.get("capital") or s(sh9.cell(r, 4).value)
        d["area_sq_km"] = num(sh9.cell(r, 5).value)
        d["census_1991"] = num(sh9.cell(r, 6).value)
        d["census_2006"] = num(sh9.cell(r, 7).value)
        d["population_projection"] = num(sh9.cell(r, 8).value)

    # --- NIN Data: enrolments ---
    nin = wb["NIN Data"]
    for r in range(2, nin.max_row + 1):
        st = canon(nin.cell(r, 1).value)
        if not st:
            continue
        d = data[st]
        d["nin_female"] = num(nin.cell(r, 2).value)
        d["nin_male"] = num(nin.cell(r, 3).value)
        d["nin_total"] = num(nin.cell(r, 4).value)

    # --- 2023 Data: total votes 2023 & 2019 ---
    d23 = wb["2023 Data"]
    for r in range(3, d23.max_row + 1):
        st = canon(d23.cell(r, 1).value)
        if not st:
            continue
        d = data[st]
        d["votes_2023"] = num(d23.cell(r, 2).value)
        d["total_votes_2019"] = num(d23.cell(r, 5).value)

    # FCT is not in Sheet9
    if not data["FCT"].get("code"):
        data["FCT"]["code"] = "FCT"
    if not data["FCT"].get("capital"):
        data["FCT"]["capital"] = "Abuja"

    # --- write module ---
    lines = ['"""State facts, statistics and 2019 governor races (from the election spreadsheet).',
             "", "Auto-generated by backend/scripts/extract_states.py. Do not edit.", '"""', "",
             "STATE_DATA = {"]
    keys = ["code", "capital", "area_sq_km", "census_1991", "census_2006", "population_projection",
            "active_phone_2021", "active_phone_2020", "newly_registered_voters_2022",
            "voters_presidential_2019", "buhari_votes_2019", "atiku_votes_2019",
            "total_votes_2019", "votes_2023", "nin_total", "nin_male", "nin_female"]
    ncand = 0
    for st in APP_STATES:
        d = data[st]
        lines.append(f"    {st!r}: {{")
        for k in keys:
            lines.append(f"        {k!r}: {d.get(k)!r},")
        lines.append('        "governor_2019": [')
        for g in d["governor_2019"]:
            ncand += 1
            lines.append(f'            {{"name": {g["name"]!r}, "party": {g["party"]!r}, "votes": {g["votes"]!r}, "position": {g["position"]!r}}},')
        lines.append("        ],")
        lines.append("    },")
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    have = lambda k: sum(1 for st in APP_STATES if data[st].get(k) is not None)
    print("states:", len(APP_STATES), "| governor candidates:", ncand)
    for k in ["code", "capital", "active_phone_2021", "newly_registered_voters_2022", "buhari_votes_2019", "nin_total", "votes_2023"]:
        print(f"  {k}: {have(k)}/37 populated")
    print("\nAbia sample:", {k: data["Abia"].get(k) for k in ["code", "capital", "active_phone_2021", "active_phone_2020", "buhari_votes_2019", "atiku_votes_2019", "nin_total"]})
    print("Abia governor 2019:", data["Abia"]["governor_2019"])
    print(f"\nWrote {OUT}")


if __name__ == "__main__":
    main()
